version: '3.8'

services:
  front-web:
    container_name: benches-web
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile
    ports:
      - '5173:80'
    volumes:
      - ./:/opt/rick-and-morty/front
